name: "Backend"
on:
  push:
    branches-ignore:
      - main
    paths:
      - api/**
      - .github/workflows/build-and-test-api.yml

concurrency:
  group: ${GITHUB_REF#refs/heads/}-api
  cancel-in-progress: true

jobs:
  test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: chat_app_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        shell: bash
    env:
      DATABASE_URL: "postgresql://postgres:password@localhost:5432/chat_app_test"
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run ESLint/Prettier
        run: yarn api:lint
      - name: Run Migrate
        run: yarn workspace api migrate:deploy
      - name: Copy .env.example to .env for test
        run: cp api/.env.example api/.env
      - name: Run Unit Test
        run: yarn api:test
      - name: Run e2e test
        run: yarn workspace api test:e2e
